CREATE DATABASE  IF NOT EXISTS `registroEmpleados`;
USE `registroEmpleados`;

create table Employees (
employee_id int AUTO_INCREMENT,
employee_name varchar(300) not null,
payment_company varchar(15) not null,
join_date date not null,
branch varchar(30) not null,
service varchar(250) not null,
primary key (employee_id)
);

INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('EUGENIA ARACELI PENA VARO','MSI','2017-03-26','Guadalajara','CEDIS ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JOSE LUIS MARTINEZ PERALTA','MSI','2018-02-21','Guadalajara','CEDIS ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JULIO CESAR RAMIREZ PEREZ','MSI','2016-11-11','Guadalajara','CEDIS ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ROBERTO JIMENEZ VELAZQUEZ','MSI','2008-09-29','Guadalajara','CEDIS ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ANSELMO CARRILLO SANCHEZ','MSI','2017-12-07','Guadalajara','COMODINES ELITE');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ARTURO MORENO RUIZ','MSI','2012-06-20','Guadalajara','COMODINES ELITE');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JOSE GUADALUPE MARTINEZ CAMARENA','MSI','2011-04-30','Guadalajara','COMODINES ELITE');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('LUIS DE LA CRUZ LUNA','MSI','2012-03-24','Guadalajara','COMODINES ELITE');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ALMA ROSA LUGO RAMIREZ','MSI','2018-09-08','Guadalajara','COMODINES MULTISERVICIO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ANTONIO GUILLEN GAONA','MSI','2017-10-14','Guadalajara','COMODINES MULTISERVICIO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('IVAN AMISADAI DE LA CRUZ PEREZ','MSI','2016-06-17','Guadalajara','COMODINES MULTISERVICIO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('VICENTE BERNARDINO MARISCAL','MSI','2015-01-21','Guadalajara','COMODINES MULTISERVICIO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('FEDERICO GOMEZ RODRIGUEZ','MSI','2015-04-09','Guadalajara','DISTRIBUIDORA LA ESTRELLA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JOSE MARTIN PADILLA OLAGUE','MSI','2017-09-01','Guadalajara','DISTRIBUIDORA LA ESTRELLA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ALBERTO ORENDAIN HERNANDEZ','MSI','2009-04-25','Guadalajara','EMMSA GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('WILBER FIGUEROA PEREZ','MSI','2011-10-01','Guadalajara','EMMSA GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('LUIS IVAN QUIROZ MORAN','MSI','2018-08-31','Guadalajara','FAC  NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MA MARCELINA FLORES HERNANDEZ','MSI','2019-01-11','Guadalajara','FAC CUBRE DESCANSO FANTASIAS AEROCOCINAS COSTENA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ERIKA GUADALUPE GONZALEZ VAZQUEZ','MSI','2019-03-29','Guadalajara','FAC CUBRE DESCANSO GPO INDITEX');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JAIME ALBERTO MOJARDIN HERNANDEZ','MSI','2018-09-16','Guadalajara','FAC CUBRE DESCANSO GPO INDITEX');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JOSE DE JESUS VAZQUEZ MORALES','MSI','2013-05-01','Guadalajara','FAC CUBRE DESCANSO GPO INDITEX');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RODRIGO ARANDA GARCIA','MSI','2019-03-27','Guadalajara','FAC CUBRE DESCANSO GPO INDITEX');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('CARLOS PEREZ BAUTISTA','MSI','2017-07-12','Guadalajara','FAC CUBRE DESCANSO GRP INDITEX GRAN PLAZA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('DAVID ZARATE LOPEZ','MSI','2019-04-04','Guadalajara','FAC CUBRE DESCANSO GRP INDITEX GRAN PLAZA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('LORENZO ANTONIO DAMIAN GOMEZ','MSI','2019-01-13','Guadalajara','FAC CUBRE DESCANSO YARA MANZANILLO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('OSCAR CECILIO PENA RAMOS','MSI','2018-05-20','Guadalajara','FAC CUBREDESCANSO HB VALLARTA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('HECTOR CASTRO RIOS','MSI','2019-01-23','Guadalajara','FAMUSA MUEBLES');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARIA DE LOS ANGELES FUENTES AVILA','MSI','2018-03-30','Guadalajara','FANTASIAS MIGUEL GDL HIDALGO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('SALVADOR OROZCO VAZQUEZ','MSI','2013-03-25','Guadalajara','FANTASIAS MIGUEL GDL HIDALGO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('VICTOR MANUEL ADAME LOPEZ','MSI','2018-10-27','Guadalajara','FANTASIAS MIGUEL GDL HIDALGO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ERICK RAUL ROLDAN RIVERA','MSI','2019-03-13','Guadalajara','FANTASIAS MIGUEL GDL OTERO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARICELA ESPINOZA BIVANCO','MSI','2018-12-09','Guadalajara','FANTASIAS MIGUEL GDL OTERO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ROGACIANO PEREZ BALTAZAR','MSI','2010-11-26','Guadalajara','FANTASIAS MIGUEL ZAPOPAN II');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARIA VIRGINIA BARAJAS MAGALLANES','MSI','2018-05-03','Guadalajara','FORSAC MEXICO SA DE CV');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RICARDO FERNANDEZ RODRIGUEZ','MSI','2018-12-24','Guadalajara','FORSAC MEXICO SA DE CV');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('EDUARDO DE JESUS VELEZ ASCENCIO','MSI','2016-07-18','Guadalajara','HB ANDARES GDL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('SERGIO HUGO PULIDO MIRELES','MSI','2018-10-26','Guadalajara','HB LANDMARK');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ISIDRO IVAN IBARRA LOPEZ','MSI','2017-09-11','Guadalajara','HB PUERTO VALLARTA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JUSTINA ROCHA FRIAS','MSI','2018-12-31','Guadalajara','HEAT Y CONTROL II');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RAYMUNDO AGUILAR BAROCIO','MSI','2017-09-20','Guadalajara','HEAT Y CONTROL II');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ANTONIO CHAVEZ BECERRA','MSI','2004-05-07','Guadalajara','HEAT AND CONTROL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('CARLOS GERARDO GUTIERREZ IBARRA','MSI','2019-01-30','Guadalajara','HEAT AND CONTROL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('FERNANDO CABRERA BARRIOS','MSI','2013-11-23','Guadalajara','HEAT AND CONTROL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JESUS ALBERTO FLORES RIVERA','MSI','2018-04-19','Guadalajara','HEAT AND CONTROL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JOSE REFUGIO LEON BERNAL','MSI','2017-09-22','Guadalajara','HEAT AND CONTROL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JUAN JOSE GARCIA ARIAS','MSI','2014-03-29','Guadalajara','HERMES GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('CARLOS FRANCISCO ROSALES RUVALCABA','MSI','2014-03-01','Guadalajara','HIGH STREET GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ISAIAS GARCIA LOPEZ','MSI','2017-05-16','Guadalajara','IDEAR ELECTRONICA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JUAN LUIS SERRANO GUTIERREZ','MSI','2015-07-27','Guadalajara','IDETRA SA DE CV');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('VICTOR MANUEL CASTANEDA HERNANDEZ','MSI','2012-07-09','Guadalajara','IDETRA SA DE CV');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ALVARO JOEL CARRILLO QUINTERO','MSI','2013-05-01','Guadalajara','IMPORTADORA SAYTO SA DE CV');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JULIAN MURO DELGADO','MSI','2010-02-27','Guadalajara','IMPORTADORA SAYTO SA DE CV');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('DAVID ELIAS QUIROZ QUIROZ','MSI','2018-07-04','Guadalajara','JEFE DE SERVICIO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('GUSTAVO PEREZ FLORES','MSI','2019-05-07','Guadalajara','KELLY IBM');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MANASES HERNANDEZ HERNANDEZ','MSI','2018-12-12','Guadalajara','KELLY IBM');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('TANIA MARIA LIMON GONZALEZ','MSI','2010-11-20','Guadalajara','KELLY IBM');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('VANESSA ELIZABETH HERNANDEZ RODRIGUEZ','MSI','2018-04-21','Guadalajara','KELLY IBM');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ALBERTO GARCIA LARA','MSI','2018-07-21','Guadalajara','la madrileNa');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JESUS RAMON ARIAS MEDINA','MSI','2012-01-27','Guadalajara','la madrileNa');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JOSE LUIS TINOCO ORTEGA','MSI','2019-02-23','Guadalajara','la madrileNa');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RAQUEL LOPEZ SOLIS','MSI','2017-10-31','Guadalajara','la madrileNa');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ISRAEL GARCIA TAPIA','MSI','2019-03-07','Guadalajara','LEFTIES GRAN PLAZA GDL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ERNESTO HERNANDEZ SANTOSCOY','MSI','2012-07-27','Guadalajara','LEGGET AND PLATT GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MA. DEL REFUGIO MUNOZ PEREZ','MSI','2017-09-09','Guadalajara','MANPOWER GDL PLAZA DEL SOL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ALMA VIOLETA ALAMOS AVILA','MSI','2018-06-07','Guadalajara','MANPOWER GDL CENTRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('NOE SALVADOR AGUAYO CASTANEDA','MSI','2015-05-27','Guadalajara','MASSIMO DUTTI GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JUAN MANUEL ROSTRO QUEZADA','MSI','2013-09-02','Guadalajara','MEDISTIK JALISCO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MANUELA MARTINEZ ALVAREZ','MSI','2019-01-18','Guadalajara','MEDISTIK JALISCO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ALBERTO HERNANDEZ MEDINA','MSI','2012-01-27','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ELVIRA MORALES SOLEDAD','MSI','2019-02-23','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('GABRIEL PALACIOS IBARRA','MSI','2019-05-17','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JOSE LUIS AYALA CONTRERAS','MSI','2018-01-16','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JUAN JOSE VALENCIA BASULTO','MSI','2012-03-16','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('LUCILA MENDOZA ARREOLA','MSI','2018-10-20','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('LUIS CARLOS NUNO MARQUEZ','MSI','2019-01-27','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MA CRISTINA LOPEZ HERNANDEZ','MSI','2018-03-26','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MA. AMELIA FRANCO VALDEZ','MSI','2019-04-27','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARIA DEL PILAR DUENAS LOPEZ','MSI','2019-03-28','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARIA ENRIQUETA SAMANO JIMENEZ','MSI','2019-03-28','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('NORMA ANGELICA SOLIS CARVAJAL','MSI','2019-01-27','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('NORMA LETICIA SUAREZ QUEVEDO','MSI','2019-03-28','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ROSA MARIA ALVARADO AGUIRRE','MSI','2018-09-09','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('VERONICA MARLET FRANCO RODRIGUEZ','MSI','2018-11-04','Guadalajara','NYPRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('CELSO MARTINEZ MERITO','MSI','2011-11-04','Guadalajara','PASCUAL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ERIC SEBASTIAN GUTIERREZ FLORES','MSI','2017-03-26','Guadalajara','PASCUAL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('FRANCISCO JAVIER CORONADO RAMIREZ','MSI','2010-02-16','Guadalajara','PASCUAL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JORGE ALBERTO VARGAS VARGAS','MSI','2016-01-22','Guadalajara','PETROAGRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JUAN JAVIER HERNANDEZ ALDANA','MSI','2019-03-13','Guadalajara','PETROAGRO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ALMA DELIA RIVERA PINA','MSI','2017-08-09','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('FRANCISCO JAVIER PEREZ FIGUEROA','MSI','2010-04-25','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('GUSTAVO GONZALEZ JACINTO','MSI','2019-02-09','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JORGE HIROKI KOBAYASHI RIVAS','MSI','2018-08-03','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JOSE DANIEL VAZQUEZ RODRIGUEZ','MSI','2019-01-09','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JULIETA CRISTINA PENA ALVIZO','MSI','2018-11-14','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARISOL GUZMAN HEREDIA','MSI','2019-02-20','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARTIN CIRILO MEDINA RAMIREZ','MSI','2015-08-15','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RICARDO ANGUIANO ARREOLA','MSI','2012-11-17','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RUBEN LOPEZ ZUNIGA','MSI','2019-03-31','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('VICENTE OROZCO VAZQUEZ','MSI','2013-06-04','Guadalajara','PLANTA ZAPOPAN');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('CESAR MORONES BAUTISTA','MSI','2011-08-27','Guadalajara','PRODUCTOS ALIMETICIOS NASA SA DE CV');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('TOMAS AMARAL FLORES','MSI','2010-09-24','Guadalajara','PRODUCTOS ALIMETICIOS NASA SA DE CV');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JUAN GABRIEL GONZALEZ OLGUIN','MSI','2017-09-15','Guadalajara','PSAP SANTA CRUZ');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARTIN RAMOS MURILLO','MSI','2019-03-13','Guadalajara','PSAP SANTA CRUZ');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ALBERTO OCHOA RODRIGUEZ','MSI','2019-01-05','Guadalajara','PULL AND BEAR PUERTO VALLARTA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ALEJANDRO MONRROY MORANDO','MSI','2019-05-15','Guadalajara','PULL AND BEAR GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ARTURO CHAVEZ ROBLES','MSI','2019-02-23','Guadalajara','SE FANTASIAS MIGUEL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('SERGIO RICARDO FLORES VENTURA','MSI','2018-04-07','Guadalajara','SE FANTASIAS MIGUEL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JORGE HERNANDEZ ALVAREZ','MSI','2013-07-04','Guadalajara','SE YVES SAINT LAURENT ANDARES');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ELIZABETH VAZQUEZ FLORES','MSI','2019-03-24','Guadalajara','SERVICIOS MOLYCOP SA DE CV');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('LIZBETH YUKARI CASTRO GOMEZ','MSI','2019-05-11','Guadalajara','SERVICIOS MOLYCOP SA DE CV');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('GUILLERMO CASTRO CASTRO','MSI','2014-06-09','Guadalajara','SOFTEK GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JAIME VILLEGAS TRUJILLO','MSI','2015-07-29','Guadalajara','SOFTEK GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('LORENA DEL ROCIO ENCISO VARGAS','MSI','2019-04-10','Guadalajara','SOFTEK GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARIA DE JESUS TAPIA CAMPOS','MSI','2017-02-04','Guadalajara','SOFTEK GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RICARDO PEREZ COVARRUBIAS','MSI','2018-12-07','Guadalajara','SOFTEK GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RICARDO GALLEGOS JIMENEZ','MSI','2013-07-01','Guadalajara','SUMITOMO PLANTA GUADALAJARA');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ENRIQUE DELGADO ALDAZ','MSI','2006-01-11','Guadalajara','TATA 2');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('HUGO DANIEL SIGALA FLORES','MSI','2019-04-13','Guadalajara','TATA 2');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RAMON PULIDO GONZALEZ','MSI','2018-10-13','Guadalajara','TATA 2');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ROBERTO SALAZAR CARREON','MSI','2011-09-23','Guadalajara','TATA 2');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ROGELIO MUNDO SOLIS','MSI','2019-06-03','Guadalajara','TATA 2');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ROSA MARIA VILLALOBOS BARAJAS','MSI','2016-02-21','Guadalajara','TATA 2');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('GERONIMO AGUILAR GONZALEZ','MSI','2019-06-17','Guadalajara','TATA 3');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('HECTOR CASTRO GOMEZ','MSI','2019-01-23','Guadalajara','TATA 3');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ISMAEL CAMACHO CARRILLO','MSI','2018-11-25','Guadalajara','TATA 3');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JAIME CAMPOS GOMEZ','MSI','2019-05-08','Guadalajara','TATA 3');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JORGE ALEJANDRO VILLALOBOS PIMENTEL','MSI','2019-04-20','Guadalajara','TATA 3');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARIA ZENAIDA BRAVO VENTURA','MSI','2019-05-15','Guadalajara','TATA 3');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ROXANA HERNANDEZ ANCELIN','MSI','2019-03-27','Guadalajara','TATA 3');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('VICTOR ALFONSO CRUZ LOPEZ','MSI','2019-05-15','Guadalajara','TATA 3');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('VIRGINIA RODRIGUEZ HERNANDEZ','MSI','2019-04-26','Guadalajara','TATA 3');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ADALBERTO ANAYA ORTIZ','MSI','2018-09-28','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ANA LAURA JIMENEZ HERNANDEZ','MSI','2019-06-23','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ANSELMO HERIBERTO GARCIA MEZA','MSI','2019-05-18','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('CHRISTIAN GARCIA RAMOS','MSI','2019-02-27','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('CLAUDIA GARCIA VALENZUELA','MSI','2019-05-30','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ELADIA MONSERRAT MARTINEZ SALAZAR','MSI','2019-05-30','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ERIKA MACRINA ALONSO JIMENEZ','MSI','2019-03-04','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('GLORIA GARCIA RAMOS','MSI','2019-04-20','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JORGE ADALBERTO QUIROZ LORENZO','MSI','2017-04-07','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARCO ANTONIO ESTRADA REYES','MSI','2019-03-07','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARGARITA GARCIA SALVADOR','MSI','2018-03-30','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARIA MARSELA GARCIA RAMOS','MSI','2018-10-13','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('SALVADOR MARTINEZ GAMINO','MSI','2019-04-07','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('VERONICA BARAJAS CONTRERAS','MSI','2018-08-11','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('VICTOR HUGO DIAZ GONZALEZ','MSI','2019-01-09','Guadalajara','TATA 4');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('GERARDO  SALVADOR VAZQUEZ JIMENEZ','MSI','2003-12-23','Guadalajara','TELECT DE MEXICO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('HECTOR DIAZ LARA','MSI','2018-11-27','Guadalajara','UNITED PARCEL SERVICE AEROPUERTO GDL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ANGEL LUQUIN ROBLES','MSI','2009-10-15','Guadalajara','UPS');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JUAN CARLOS LOPEZ VALLARTA','MSI','2011-10-07','Guadalajara','UPS');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('EDSON ANIBAL PALACIOS MARQUEZ','MSI','2017-10-04','Guadalajara','VIVRI MEXICO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JAVIER GARCIA RAMIREZ','MSI','2017-05-13','Guadalajara','VIVRI MEXICO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JOSE ALBERTO PEREZ URENDA','MSI','2015-12-29','Guadalajara','VIVRI MEXICO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARGARITA ORTEGA CISNEROS','MSI','2019-01-09','Guadalajara','VIVRI MEXICO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARIA LUISA MOTA TORRES','MSI','2019-01-06','Guadalajara','VIVRI MEXICO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('EFREN VILLA MALDONADO','MSI','2019-04-08','Guadalajara','YARA MANZANILLO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('ISRAEL MENDOZA CERVANTES','MSI','2019-04-04','Guadalajara','YARA MANZANILLO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RAFAEL ENRIQUE MORFIN RAZON','MSI','2018-07-01','Guadalajara','YARA MANZANILLO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JULIA ALEMAN PRECIADO','MSI','2019-03-07','Guadalajara','ZARA GRAN PLAZA GDL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARTIN LUNA MORENO','MSI','2017-05-05','Guadalajara','ZARA GRAN PLAZA GDL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('RAFAEL ENRIQUE MORFIN RAZON','MSI','2018-07-01','Guadalajara','YARA MANZANILLO');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('JULIA ALEMAN PRECIADO','MSI','2019-03-07','Guadalajara','ZARA GRAN PLAZA GDL');
INSERT INTO Employees (employee_name, payment_company, join_date, branch, service) VALUES ('MARTIN LUNA MORENO','MSI','2017-05-05','Guadalajara','ZARA GRAN PLAZA GDL');

